Basic Queries
--Display all customers.
select customer_name  from customers;

--Display all products.
select product_name from products;

--List all orders sorted by Order Date.
select order_id,order_date 
from sales_orders
order by order_date asc;

--Show distinct customer cities.

select distinct city
from customers;

--Display the top 10 highest-priced products.
select product_name,price
from(
select product_name,price
from products
order by price desc
)
where rownum<=10;


--Customers from Bengaluru.

select customer_name,customer_id,city
from customers
where city='Bangalore';

--Products costing more than ?3000.
select product_id,product_name,price
from products
where price>3000;

--Orders placed between two dates.
select order_id,order_date
from sales_orders
where order_date between '20-SEP-25' and '27-SEP-25';

--Customers whose names start with 'A'.
select customer_name
from customers
where customer_name like 'A%';

--Products belonging to Electronics.

select p.product_id,p.product_name,c.category_id
from products p
inner join categories c
on c.category_id=p.category_id
where category_name='Electronics';

--aggregations

-- Total sales for each order
select order_id,sum(quantity*unit_price)
from sales_order_details
group by order_id;

-- total sales of the company
select sum(quantity*unit_price)
from sales_order_details;

--Average order value.
select avg(avg_order) as avg_order_value
from
(
select order_id,sum(quantity*unit_price) as avg_order
from sales_order_details
group by order_id
);

--Highest-priced product.
select product_id,product_name,price
from products
where price = (select max(price) from products);

Lowest-priced product.

select product_id,product_name,price
from products
where price = (select min(price) from products);



--Number of customers.

select count(*)
from customers;

-- Business Analysis

Revenue by category.

select category_name,sum(quantity*unit_price) as revenue_by_category
from products p
inner join sales_order_details so
on so.product_id=p.product_id
inner join categories c
on p.category_id=c.category_id
group by category_name
order by revenue_by_category desc;

--Orders by employee.
select e.employee_name,e.employee_id,count(so.order_id) as orders_by_employee
from sales_orders so
inner join employees e
on so.employee_id=e.employee_id
group by e.employee_name,e.employee_id
order by orders_by_employee desc;

--Sales by state.

select r.region_name,sum(quantity*unit_price) as sales_by_state
from sales_orders o
inner join sales_order_details so
on o.order_id=so.order_id
inner join regions r
on o.region_id=r.region_id
group by r.region_name
order by sales_by_state desc;

--Monthly sales summary

select to_char(o.order_date,'MM'),sum(quantity*unit_price) as sales_by_state
from sales_orders o
inner join sales_order_details so
on o.order_id=so.order_id
inner join regions r
on o.region_id=r.region_id
group by to_char(o.order_date,'MM')
order by sales_by_state desc;


--Categories with revenue greater than ?5,00,000.


select category_name,sum(quantity*unit_price) as revenue_by_category
from products p
inner join sales_order_details so
on so.product_id=p.product_id
inner join categories c
on p.category_id=c.category_id
group by category_name
having sum(quantity*unit_price) >500000
order by revenue_by_category desc;

--Customer names with their orders.
select customer_name,order_id,order_date
from customers c
inner join sales_orders o
on c.customer_id=o.customer_id;

--Order details with product names.
select so.order_id,so.order_detail_id,p.product_name
from sales_order_details so
inner join products p
on so.product_id=p.product_id;


--Products with supplier names.
select product_id,product_name,supplier_name
from products p
inner join suppliers s
on p.supplier_id=s.supplier_id;

--Employees with the orders they handled.
select employee_name,order_id
from employees e
inner join sales_orders o
on e.employee_id=o.employee_id;

-- Customers who have never placed an order.
select customer_name,order_id
from customers c
left join sales_orders o
on c.customer_id=o.customer_id
where o.order_id is null;

-- Products that have never been sold.
select p.product_name,p.product_name
from products p
left join sales_order_details o
on p.product_id=o.product_id
where order_id is null;

-- Total revenue generated by each supplier.
select s.supplier_id,s.supplier_name,sum(so.quantity*so.unit_price) as total_revenue
from products p
inner join sales_order_details so
on p.product_id=so.product_id
inner join suppliers s
on p.supplier_id=s.supplier_id
group by s.supplier_id,s.supplier_name
order by total_revenue desc;

-- Orders along with customer and employee information.
select s.order_id,s.order_date,c.customer_name,c.gender,e.employee_name,e.designation
from sales_orders s
inner join customers c
on s.customer_id=c.customer_id
inner join employees e
on s.employee_id=e.employee_id;

--Average order value by customer.
SELECT customer_id,
       customer_name,
       AVG(order_total) AS avg_order_value
FROM (
    SELECT so.order_id,
           c.customer_id,
           c.customer_name,
           SUM(s.quantity * s.unit_price) AS order_total
    FROM sales_orders so
    JOIN sales_order_details s
      ON so.order_id = s.order_id
    JOIN customers c
      ON so.customer_id = c.customer_id
    GROUP BY so.order_id,
             c.customer_id,
             c.customer_name
)
GROUP BY customer_id, customer_name
ORDER BY avg_order_value DESC;


--Top 5 customers by total spending.
select customer_id,customer_name,total_spend
from
(
select c.customer_id,c.customer_name,sum(p.amount) as total_spend
from sales_orders s
inner join payments p
on s.order_id=p.order_id
inner join customers c
on s.customer_id=c.customer_id
group by c.customer_id,c.customer_name
order by total_spend desc
)
where rownum<=5;


--Top Selling Products

select p.product_name,sum(so.quantity) as top_selling
from products p
inner join sales_order_details so
on p.product_id=so.product_id
group by p.product_name
order by top_selling desc;

--Employee Revenue

SELECT
e.employee_name,
SUM(sod.quantity*sod.unit_price) revenue
FROM Employees e
JOIN Sales_Orders so
ON e.employee_id=so.employee_id
JOIN Sales_Order_Details sod
ON so.order_id=sod.order_id
GROUP BY e.employee_name
ORDER BY revenue DESC;

--Payment Mode Analysis
select p.payment_mode,sum(amount) 
from payments p
group by p.payment_mode;

--Return Analysis
SELECT
p.product_name,
COUNT(*) as total_returns
FROM Returns r
INNER JOIN Products p
ON r.product_id=p.product_id
GROUP BY p.product_name
ORDER BY total_returns DESC;
--Monthly orders
SELECT
TO_CHAR(order_date,'Mon YYYY'),
COUNT(*)
FROM Sales_Orders
GROUP BY TO_CHAR(order_date,'Mon YYYY')
ORDER BY MIN(order_date);

--Inventory Value
SELECT
SUM(price*stock_quantity)
FROM Products;
